services:
  hono-app:
    build: .
    command: ["/app/startup.sh"]
    env_file:
      - .env
    ports:
      - "5000:5000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./logs:/app/logs
      # - ./crontab:/etc/crontabs/root
    networks:
      - nakhoda-network
    privileged: true  # Add this line for ARM64 compatibility

networks:
  nakhoda-network:
    external: true    # This allows connecting to existing network
