services:
  hono-app:
    build: .
    command: ["sh", "-c", "crond && npm run start"]
    env_file:
      - .env
    ports:
      - "5000:5000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./logs:/app/logs
    networks:
      - nakhoda-network
    depends_on:
      - postgis

networks:
  nakhoda-network:
    external: true    # This allows connecting to existing network
