services:
  hono-app:
    build: .
    command: ["sh", "-c", "crond && npm run start"]
    env_file:
      - .env
    network_mode: "host"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./logs:/app/logs
